name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy Documentation Files
        run: |
          cp README.md addons/aurailus.unexport_my_props/README.md
          cp LICENSE.md addons/aurailus.unexport_my_props/LICENSE.md

      - name: Copy Files to Artifact Dir
        run: |
          mkdir artifact
          mv addons artifact/addons
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: UnexportMyProps
          path: artifact
